/* DO NOT EDIT THIS FILE - it is machine generated */
#include "base.h"
#include "utils.h"
#include "cJSON/cJSON.h"
/* Header for class com_use_tempsdk_jni_DeviceInfo */

#ifndef _Included_com_use_tempsdk_jni_DeviceInfo
#define _Included_com_use_tempsdk_jni_DeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_use_tempsdk_jni_DeviceInfo
 * Method:    message
 * Signature: (Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_use_tempsdk_jni_DeviceInfo_message
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif

char* getPackage(JNIEnv* env, jobject jpkgobject);

char *getCpuName(JNIEnv *env);

char* getTotalMemory(JNIEnv* env);

char* getMainBoard(JNIEnv* env);

char *getKernel(JNIEnv *env);

jobject getTelephoneManagerObj(JNIEnv *env, jobject jCtxObj);

char* getInfo4TM(JNIEnv *env, jobject tmObj, const char *methodName);

jobject getWifiManagerObj(JNIEnv *env, jobject jCtxObj);

char* getMacAddress(JNIEnv *env, jobject wmObj);


//新添加
char* isWhatTypeOperate(JNIEnv * env,jobject ctx);//重复 删掉

jboolean isEmulate4simple(JNIEnv *env, jobject ctx);
jboolean isNotEmpty(JNIEnv *env, jstring str);
jboolean startWith(JNIEnv *env, jstring str, jstring key);
jstring toLowerCase(JNIEnv *env, jstring str);
jstring readFile(JNIEnv *env, jstring path);
jboolean hasQEmuDrivers(JNIEnv *env);
jstring getOsImsi(JNIEnv *env, jobject ctx);
jobject getTelephoneManager(JNIEnv *env, jobject ctx);
jclass getTelephoneManagerClass(JNIEnv *env);
jstring isEmulate4simple1(JNIEnv *env, jobject ctx);

//继续增加
jint getSDKVersionInt(JNIEnv *env);
char *getSdkVersionChar();
char *getBuild(const char *key, const char *def);
int property_get(const char *key, char *value, const char *default_value);
char *getRelease();
jint getSimCount(JNIEnv *env, jobject ctx);
jstring getOsImsi(JNIEnv *env, jobject ctx);

jstring getSimOperatorName(JNIEnv *env, jobject ctx);
jstring getUUID(JNIEnv *env);
jstring getInstallTime(JNIEnv *env, jobject ctx);
jstring getLocal(JNIEnv *env, jobject ctx);
jstring getPackageVersion(JNIEnv *env, jobject ctx);
jstring getCpu(JNIEnv *env);
jstring getProduct(JNIEnv *env);
jstring getNetworkType(JNIEnv *env, jobject ctx);
jstring getPhoneNumber(JNIEnv *env, jobject ctx);//获取不了
jstring getCellid(JNIEnv *env, jobject ctx);
jstring getLac(JNIEnv *env, jobject ctx);
jstring getSerialNo(JNIEnv *env);
jstring getAndroidId(JNIEnv *env, jobject ctx);
#endif
